name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Max Kreminski
website: ${project.url}

main: com.remypas.wikisearch.WikiSearchPlugin

commands:
  wikisearch:
    description: Searches for the specified search terms via the specified wiki.
    usage: 'Usage: /<command> <search terms> [-bro] [-to:player] [-via:wiki]'
    aliases: [search, wiki, ws]
    permission: wikisearch.sendsearchresultsto.self

permissions:
  wikisearch.*:
    description: May make full use of all plugin features
    children:
      wikisearch.searchvia.*: true
      wikisearch.sendsearchresultsto.*: true
  wikisearch.searchvia.*:
    description: May search via any available wiki
  wikisearch.sendsearchresultsto.*:
    description: May send search results to anyone
    children:
      wikisearch.sendsearchresultsto.globalchat: true
      wikisearch.sendsearchresultsto.otherplayer: true
      wikisearch.sendsearchresultsto.self: true
